### ISSUE TITLE
Möglicher Error wenn getList() null ist

### ISSUE THREAD

**Issue by nribinin** [TGM-HIT/sew9-2425-worttrainer-Ubetterbisoft#1]
Es wird vorausgesetzt, dass getList() nie null ist und mindestens so viele Elemente hat wie die Anzahl der korrekten Versuche. Wenn dies nicht der Fall ist, könnte ein IndexOutOfBoundsException auftreten.

**Comment by Ubetterbisoft** [comment]
Danke für dein Issue, ich arbeite bereits an der implementierung

**Comment by Ubetterbisoft** [comment]
Danke änderungen wurden implementiert
